model:
  name: "srgan"  # Options: "srcnn" or "srgan"
  device: "cuda"  # Options: "cuda" or "cpu"

# Dataset Configuration
dataset:
  name: "DIV2K"
  scale_factor: 4  # Upscaling factor: 2, 3, 4, 8
  train_hr_dir: "DIV2K/DIV2K_train_HR"
  train_lr_dir: "DIV2K/DIV2K_train_LR_bicubic/X4"
  valid_hr_dir: "DIV2K/DIV2K_valid_HR"
  valid_lr_dir: "DIV2K/DIV2K_valid_LR_bicubic/X4"

  # Data preprocessing
  hr_crop_size: 256  # Size of HR patches for training
  augmentation:
    horizontal_flip: true
    vertical_flip: true
    rotation: true  # 90-degree rotations

  # Normalization
  normalization:
    enabled: true
    lr_norm_type: "zero_one"       # For LR images: [0, 1]
    hr_norm_type: "minus_one_one"  # For HR images: [-1, 1]

# Training Configuration
training:
  epochs: 100
  batch_size: 32
  num_workers: 4  # DataLoader workers
  reproducible: false # Set to true for strict reproducibility

  # Learning rate settings
  learning_rate:
    generator: 0.0002  # For SRGAN generator or SRCNN
    discriminator: 0.00005  # For SRGAN discriminator only

  # Learning rate scheduler
  scheduler:
    enabled: true
    type: "plateau"  # Options: "step", "cosine", "plateau", "two_stage"

    # Plateau scheduler settings
    patience: 2      # How many epochs to wait for improvement
    factor: 0.5       # Factor to reduce LR by (e.g., 1e-4 -> 5e-5)
    min_lr: 0.000001  # Minimum learning rate

    # Step scheduler
    step_size: 50
    gamma: 0.5

    # two_stage scheduler
    milestone: 10  # Epoch at which to decay the learning rate
    decay_factor: 0.1 # Factor to multiply LR by (e.g., 1e-4 -> 1e-5 means 0.1)

  # Checkpointing
  checkpoint:
    save_interval: 10  # Save every N epochs
    save_best: true  # Save best model based on validation metric
    metric: "psnr"  # Metric to monitor for best model

  # Early stopping
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001

  # Mixed precision training
  use_amp: true  # Automatic mixed precision

  gradient_clipping:
    enabled: true
    max_norm: 1.0

# SRCNN-specific Configuration
srcnn:
  # Network architecture
  num_channels: 3  # Input/output channels (3 for RGB)
  f1: 64  # Number of filters in first layer
  f2: 32  # Number of filters in second layer
  kernel_sizes: [9, 1, 5]  # Kernel sizes for each layer

  # Loss function
  loss_type: "mse"  # Options: "mse" or "l1"

  init_type: "kaiming" # Options: "kaiming" or "normal"
  padding_mode: "same"  # Options: "same" or "valid"

# SRGAN-specific Configuration
srgan:
  # Generator architecture
  generator:
    num_channels: 3
    num_features: 64
    num_blocks: 16  # Number of residual blocks
    final_activation: "none"  # Options: "tanh" or "none"
    use_batch_norm: false
    pretrained_model_path: ""

  # Discriminator architecture
  discriminator:
    num_channels: 3
    num_features: 64

  # Loss configuration
  loss:
    content_loss: "vgg"  # Options: "mse", "l1", or "vgg"
    vgg_layer: "relu5_4"  # VGG feature layer for perceptual loss
    content_weight: 1.0
    adversarial_weight: 0.001

    # for discriminator regularization
    label_smoothing:
      enabled: true
      factor: 0.1 # Use labels [0.9, 1.0] for real and [0.0, 0.1] for fake

  # Training strategy
  pretrain:
    enabled: true
    epochs: 30              # Number of epochs for pre-training only
    validation_interval: 10  # How often to validate during pre-training
    checkpoint_interval: 10  # How often to save checkpoints during pre-training

 # for GAN training balance
  training_ratio:
    enabled: true
    generator_steps: 1      # Number of updates for G
    discriminator_steps: 5  # Number of updates for D

# Validation Configuration
validation:
  interval: 10  # Validate every N epochs
  save_images: true  # Save sample images during validation
  num_samples: 5  # Number of sample images to save

# Logging Configuration
logging:
  level: "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR"
  console: true  # Log to console
  file: true  # Log to file

# Output Directories
output:
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  result_dir: "results"

# Metrics to track
metrics:
  - "psnr"
  - "ssim"
  - "loss"

visualization:
  enabled: true
  style: "seaborn-v0_8-darkgrid" # Style for plots (e.g., "ggplot", "seaborn-v0_8-whitegrid")
  save_interim_plots: true     # Save plots whenever a new best model is found
  image_format: "png"          # Format for saved plots ("png", "svg", "pdf")


evaluation:
  checkpoint_path: "checkpoints/srgan/checkpoint_epoch_20.pth"
  output_dir: "evaluation"
  num_comparison_images: 10
  batch_size: 1